from datetime import date
from models import Job


def build_subject(jobs: list[Job], run_date: date) -> str:
    if not jobs:
        return f"[Job Digest] {run_date} — No new matches today"
    by_market: dict[str, int] = {}
    for job in jobs:
        by_market[job.market] = by_market.get(job.market, 0) + 1
    market_str = ", ".join(f"{m.upper()}: {c}" for m, c in sorted(by_market.items()))
    return f"[Job Digest] {run_date} — {len(jobs)} new matches ({market_str})"


def build_email_html(jobs: list[Job], run_date: date) -> str:
    if not jobs:
        return f"<p>No new matches today ({run_date}). The tool ran successfully.</p>"

    rows = []
    for job in jobs:
        industry = job.industry or "—"
        stage = job.stage or "—"
        sources = ", ".join(job.sources)
        rows.append(f"""
<tr style="border-bottom:1px solid #eee">
  <td style="padding:12px 8px">
    <strong><a href="{job.url}" style="color:#1a73e8">{job.title}</a></strong>
    — {job.company} ({job.market.upper()})<br>
    <small>Industry: {industry} &nbsp;|&nbsp; Stage: {stage} &nbsp;|&nbsp; Sources: {sources}</small>
  </td>
</tr>""")

    rows_html = "\n".join(rows)
    return f"""<html><body style="font-family:sans-serif;max-width:700px;margin:auto">
<h2 style="color:#333">Job Digest — {run_date}</h2>
<p>{len(jobs)} new matches</p>
<table style="width:100%;border-collapse:collapse">
{rows_html}
</table>
<hr><p style="color:#999;font-size:12px">Generated by job-aggregator</p>
</body></html>"""
