from datetime import date
from models import Job

_MARKET_LABELS = {
    "tw": "Taiwan (TW)",
    "jp": "Japan (JP)",
    "sg": "Singapore (SG)",
}


def build_subject(jobs: list[Job], run_date: date) -> str:
    if not jobs:
        return f"[Job Digest] {run_date} — No new matches"
    by_market: dict[str, int] = {}
    for job in jobs:
        by_market[job.market] = by_market.get(job.market, 0) + 1
    market_str = ", ".join(f"{m.upper()} {c}" for m, c in sorted(by_market.items()))
    return f"[Job Digest] {run_date} — {len(jobs)} new matches ({market_str})"


def _job_row(job: Job) -> str:
    sources = ", ".join(job.sources)
    company_part = f"{job.company}" if job.company else ""
    location_part = job.location if job.location else ""
    meta_parts = [p for p in [company_part, location_part] if p]
    meta_str = " · ".join(meta_parts)
    logo_td = ""
    if job.logo_url:
        logo_td = f'<td style="padding:12px 4px 12px 8px;width:48px;vertical-align:top"><img src="{job.logo_url}" width="40" height="40" style="object-fit:contain;border-radius:4px" alt=""></td>'
    else:
        logo_td = '<td style="padding:12px 4px 12px 8px;width:48px"></td>'
    return f"""
<tr style="border-bottom:1px solid #eee">
  {logo_td}
  <td style="padding:12px 8px">
    <strong><a href="{job.url}" style="color:#1a73e8">{job.title}</a></strong><br>
    <span style="color:#555">{meta_str}</span><br>
    <small style="color:#999">via {sources}</small>
  </td>
</tr>"""


def build_email_html(jobs: list[Job], run_date: date) -> str:
    if not jobs:
        return f"<p>No new job matches ({run_date}). Pipeline ran successfully.</p>"

    # Group by market, in a stable order
    by_market: dict[str, list[Job]] = {}
    for job in jobs:
        by_market.setdefault(job.market, []).append(job)

    sections_html = ""
    for market in sorted(by_market.keys()):
        label = _MARKET_LABELS.get(market, market.upper())
        rows_html = "".join(_job_row(j) for j in by_market[market])
        sections_html += f"""
<h3 style="color:#444;margin:28px 0 6px;padding-bottom:6px;border-bottom:2px solid #ddd">{label} — {len(by_market[market])} positions</h3>
<table style="width:100%;border-collapse:collapse">
{rows_html}
</table>"""

    return f"""<html><body style="font-family:sans-serif;max-width:700px;margin:auto">
<h2 style="color:#333">Job Digest — {run_date}</h2>
<p style="color:#666">{len(jobs)} new matches</p>
{sections_html}
<hr><p style="color:#999;font-size:12px">Generated by job-aggregator</p>
</body></html>"""
